### ISSUE TITLE
As technically savy user, I want to see badges with code coverage so that I can gauge the care the programmers put into this project

### ISSUE THREAD

**Issue by Aequivinius** [Aequivinius/zu-bbbearbeiten-stateless#20]
# Acceptance Criteria

|     Given      |       When        |          Then          |
| :------------: | :---------------: | :--------------------: |
| I open the repo | I look at the `readme.md` | I see a shiny badge |

# Subtasks
- [ ] Generate coverage report on PR, upload it to Coveralls
- [ ] Get coveralls URL
- [ ] Add to `readme.md`
