### ISSUE TITLE
As a technically savvy user with chill to fiddle with dependencies, I want to download a docker image so that I can fire up the app easily no matter what.

### ISSUE THREAD

**Issue by Aequivinius** [Aequivinius/zu-bbbearbeiten-stateless#28]
# Acceptance Criteria

|     Given      |       When        |          Then          |
| :------------: | :---------------: | :--------------------: |
| I donwloaded the docker image | `docker run -d -p 5000:5000 flask-app` | I can use the app |

# Subtasks
- [x] Create docker locally
- [x] Create docker image with an action
- [x] Upload action to packages
