### ISSUE TITLE
As <role>, I want <something> so that <something>

### ISSUE THREAD

**Issue by GabrielBischof** [Aequivinius/zu-bbbearbeiten-stateless#57]
## Acceptance Criteria

|        Given        |             When             |              Then               |
| :-----------------: | :--------------------------: | :-----------------------------: |
| Eine Funktion ist implementiert | Ich führe den Test für die Funktion aus | Die Funktion gibt die erwarteten Ergebnisse zurück |

## Subtasks
- [x] Die Funktion wird mit Testdaten getestet.
- [ ] Test für den Edge Case hinzufügen.
- [ ] Test für fehlerhafte Eingabewerte hinzufügen.
